
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/appcache/appcache_info.mojom
//

package org.chromium.blink.mojom;

import org.chromium.mojo.bindings.DeserializationException;

public final class AppcacheInfoConstants {


    
    public static final long APP_CACHE_NO_CACHE_ID = (long) 0L;



    
    public static final long APP_CACHE_NO_RESPONSE_ID = (long) 0L;



    
    public static final long APP_CACHE_UNKNOWN_CACHE_ID = (long) -1L;



    private AppcacheInfoConstants() {}

}