
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/blob/blob.mojom
//

package org.chromium.blink.mojom;

import org.chromium.mojo.bindings.DeserializationException;


public interface BlobReaderClient extends org.chromium.mojo.bindings.Interface {



    public interface Proxy extends BlobReaderClient, org.chromium.mojo.bindings.Interface.Proxy {
    }

    Manager<BlobReaderClient, BlobReaderClient.Proxy> MANAGER = BlobReaderClient_Internal.MANAGER;


    void onCalculatedSize(
long totalSize, long expectedContentSize);



    void onComplete(
int status, long dataLength);


}
