
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     media/mojo/interfaces/watch_time_recorder.mojom
//

package org.chromium.media.mojom;

import org.chromium.mojo.bindings.DeserializationException;


class WatchTimeRecorderProvider_Internal {

    public static final org.chromium.mojo.bindings.Interface.Manager<WatchTimeRecorderProvider, WatchTimeRecorderProvider.Proxy> MANAGER =
            new org.chromium.mojo.bindings.Interface.Manager<WatchTimeRecorderProvider, WatchTimeRecorderProvider.Proxy>() {
    
        public String getName() {
            return "media::mojom::WatchTimeRecorderProvider";
        }
    
        public int getVersion() {
          return 0;
        }
    
        public Proxy buildProxy(org.chromium.mojo.system.Core core,
                                org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            return new Proxy(core, messageReceiver);
        }
    
        public Stub buildStub(org.chromium.mojo.system.Core core, WatchTimeRecorderProvider impl) {
            return new Stub(core, impl);
        }
    
        public WatchTimeRecorderProvider[] buildArray(int size) {
          return new WatchTimeRecorderProvider[size];
        }
    };


    private static final int ACQUIRE_WATCH_TIME_RECORDER_ORDINAL = 0;


    static final class Proxy extends org.chromium.mojo.bindings.Interface.AbstractProxy implements WatchTimeRecorderProvider.Proxy {

        Proxy(org.chromium.mojo.system.Core core,
              org.chromium.mojo.bindings.MessageReceiverWithResponder messageReceiver) {
            super(core, messageReceiver);
        }


        @Override
        public void acquireWatchTimeRecorder(
PlaybackProperties properties, org.chromium.mojo.bindings.InterfaceRequest<WatchTimeRecorder> recorder) {

            WatchTimeRecorderProviderAcquireWatchTimeRecorderParams _message = new WatchTimeRecorderProviderAcquireWatchTimeRecorderParams();

            _message.properties = properties;

            _message.recorder = recorder;


            getProxyHandler().getMessageReceiver().accept(
                    _message.serializeWithHeader(
                            getProxyHandler().getCore(),
                            new org.chromium.mojo.bindings.MessageHeader(ACQUIRE_WATCH_TIME_RECORDER_ORDINAL)));

        }


    }

    static final class Stub extends org.chromium.mojo.bindings.Interface.Stub<WatchTimeRecorderProvider> {

        Stub(org.chromium.mojo.system.Core core, WatchTimeRecorderProvider impl) {
            super(core, impl);
        }

        @Override
        public boolean accept(org.chromium.mojo.bindings.Message message) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.NO_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.interfacecontrol.InterfaceControlMessagesConstants.RUN_OR_CLOSE_PIPE_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRunOrClosePipe(
                                WatchTimeRecorderProvider_Internal.MANAGER, messageWithHeader);
            
            
            
            
            
                    case ACQUIRE_WATCH_TIME_RECORDER_ORDINAL: {
            
                        WatchTimeRecorderProviderAcquireWatchTimeRecorderParams data =
                                WatchTimeRecorderProviderAcquireWatchTimeRecorderParams.deserialize(messageWithHeader.getPayload());
            
                        getImpl().acquireWatchTimeRecorder(data.properties, data.recorder);
                        return true;
                    }
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }

        @Override
        public boolean acceptWithResponder(org.chromium.mojo.bindings.Message message, org.chromium.mojo.bindings.MessageReceiver receiver) {
            try {
                org.chromium.mojo.bindings.ServiceMessage messageWithHeader =
                        message.asServiceMessage();
                org.chromium.mojo.bindings.MessageHeader header = messageWithHeader.getHeader();
                if (!header.validateHeader(org.chromium.mojo.bindings.MessageHeader.MESSAGE_EXPECTS_RESPONSE_FLAG)) {
                    return false;
                }
                switch(header.getType()) {
            
                    case org.chromium.mojo.bindings.interfacecontrol.InterfaceControlMessagesConstants.RUN_MESSAGE_ID:
                        return org.chromium.mojo.bindings.InterfaceControlMessagesHelper.handleRun(
                                getCore(), WatchTimeRecorderProvider_Internal.MANAGER, messageWithHeader, receiver);
            
            
            
            
                    default:
                        return false;
                }
            } catch (org.chromium.mojo.bindings.DeserializationException e) {
                System.err.println(e.toString());
                return false;
            }
        }
    }


    
    static final class WatchTimeRecorderProviderAcquireWatchTimeRecorderParams extends org.chromium.mojo.bindings.Struct {
    
        private static final int STRUCT_SIZE = 24;
        private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(24, 0)};
        private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
        public PlaybackProperties properties;
        public org.chromium.mojo.bindings.InterfaceRequest<WatchTimeRecorder> recorder;
    
        private WatchTimeRecorderProviderAcquireWatchTimeRecorderParams(int version) {
            super(STRUCT_SIZE, version);
        }
    
        public WatchTimeRecorderProviderAcquireWatchTimeRecorderParams() {
            this(0);
        }
    
        public static WatchTimeRecorderProviderAcquireWatchTimeRecorderParams deserialize(org.chromium.mojo.bindings.Message message) {
            return decode(new org.chromium.mojo.bindings.Decoder(message));
        }
    
        /**
         * Similar to the method above, but deserializes from a |ByteBuffer| instance.
         *
         * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
         */
        public static WatchTimeRecorderProviderAcquireWatchTimeRecorderParams deserialize(java.nio.ByteBuffer data) {
            if (data == null)
                return null;
    
            return deserialize(new org.chromium.mojo.bindings.Message(
                    data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
        }
    
        @SuppressWarnings("unchecked")
        public static WatchTimeRecorderProviderAcquireWatchTimeRecorderParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
            if (decoder0 == null) {
                return null;
            }
            decoder0.increaseStackDepth();
            WatchTimeRecorderProviderAcquireWatchTimeRecorderParams result;
            try {
                org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
                result = new WatchTimeRecorderProviderAcquireWatchTimeRecorderParams(mainDataHeader.elementsOrVersion);
                if (mainDataHeader.elementsOrVersion >= 0) {
                    
                    org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, false);
                    result.properties = PlaybackProperties.decode(decoder1);
                }
                if (mainDataHeader.elementsOrVersion >= 0) {
                    
                    result.recorder = decoder0.readInterfaceRequest(16, false);
                }
            } finally {
                decoder0.decreaseStackDepth();
            }
            return result;
        }
    
        @SuppressWarnings("unchecked")
        @Override
        protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
            org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
            
            encoder0.encode(this.properties, 8, false);
            
            encoder0.encode(this.recorder, 16, false);
        }
    
        /**
         * @see Object#equals(Object)
         */
        @Override
        public boolean equals(Object object) {
            if (object == this)
                return true;
            if (object == null)
                return false;
            if (getClass() != object.getClass())
                return false;
            WatchTimeRecorderProviderAcquireWatchTimeRecorderParams other = (WatchTimeRecorderProviderAcquireWatchTimeRecorderParams) object;
            if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.properties, other.properties))
                return false;
            if (!org.chromium.mojo.bindings.BindingsHelper.equals(this.recorder, other.recorder))
                return false;
            return true;
        }
    
        /**
         * @see Object#hashCode()
         */
        @Override
        public int hashCode() {
            final int prime = 31;
            int result = prime + getClass().hashCode();
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(this.properties);
            result = prime * result + org.chromium.mojo.bindings.BindingsHelper.hashCode(this.recorder);
            return result;
        }
    }



}
