
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/digitally_signed.mojom
//

package org.chromium.network.mojom;

import org.chromium.mojo.bindings.DeserializationException;

public final class HashAlgorithm {


    public static final int HASH_ALGO_NONE = (int) (0L);

    public static final int HASH_ALGO_MD5 = (int) (1L);

    public static final int HASH_ALGO_SHA1 = (int) (2L);

    public static final int HASH_ALGO_SHA224 = (int) (3L);

    public static final int HASH_ALGO_SHA256 = (int) (4L);

    public static final int HASH_ALGO_SHA384 = (int) (5L);

    public static final int HASH_ALGO_SHA512 = (int) (6L);

    public static final int MIN_VALUE = (int) (0);
    public static final int MAX_VALUE = (int) (6);

    private static final boolean IS_EXTENSIBLE = false;

    public static boolean isKnownValue(int value) {
        switch (value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
                return true;
        }
        return false;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value))
            return;

        throw new DeserializationException("Invalid enum value.");
    }

    private HashAlgorithm() {}

}