
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/base/video_codecs.h

package org.chromium.media;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VideoCodec.kUnknownVideoCodec, VideoCodec.kCodecH264, VideoCodec.kCodecVC1,
    VideoCodec.kCodecMPEG2, VideoCodec.kCodecMPEG4, VideoCodec.kCodecTheora, VideoCodec.kCodecVP8,
    VideoCodec.kCodecVP9, VideoCodec.kCodecHEVC, VideoCodec.kCodecDolbyVision,
    VideoCodec.kVideoCodecMax
})
@Retention(RetentionPolicy.SOURCE)
public @interface VideoCodec {
  /**
   * These values are histogrammed over time; do not change their ordinal values.  When deleting a
   * codec replace it with a dummy value; when adding a codec, do so at the bottom (and update
   * kVideoCodecMax).
   */
  int kUnknownVideoCodec = 0;
  int kCodecH264 = 1;
  int kCodecVC1 = 2;
  int kCodecMPEG2 = 3;
  int kCodecMPEG4 = 4;
  int kCodecTheora = 5;
  int kCodecVP8 = 6;
  int kCodecVP9 = 7;
  int kCodecHEVC = 8;
  int kCodecDolbyVision = 9;
  /**
   * DO NOT ADD RANDOM VIDEO CODECS! The only acceptable time to add a new codec is if there is
   * production code that uses said codec in the same CL.
   */
  int kVideoCodecMax = 9;
}
