
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../components/dom_distiller/core/experiments.h

package org.chromium.chrome.browser.dom_distiller;

import android.support.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    DistillerHeuristicsType.NONE, DistillerHeuristicsType.OG_ARTICLE,
    DistillerHeuristicsType.ADABOOST_MODEL, DistillerHeuristicsType.ALL_ARTICLES,
    DistillerHeuristicsType.ALWAYS_TRUE
})
@Retention(RetentionPolicy.SOURCE)
public @interface DistillerHeuristicsType {
  int NONE = 0;
  int OG_ARTICLE = 1;
  int ADABOOST_MODEL = 2;
  int ALL_ARTICLES = 3;
  int ALWAYS_TRUE = 4;
}
