
// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/device/public/mojom/sensor.mojom
//

package org.chromium.device.mojom;

import org.chromium.mojo.bindings.DeserializationException;

public final class SensorType {


    public static final int AMBIENT_LIGHT = 0;

    public static final int PROXIMITY = AMBIENT_LIGHT + 1;

    public static final int ACCELEROMETER = PROXIMITY + 1;

    public static final int LINEAR_ACCELERATION = ACCELEROMETER + 1;

    public static final int GYROSCOPE = LINEAR_ACCELERATION + 1;

    public static final int MAGNETOMETER = GYROSCOPE + 1;

    public static final int PRESSURE = MAGNETOMETER + 1;

    public static final int ABSOLUTE_ORIENTATION_EULER_ANGLES = PRESSURE + 1;

    public static final int ABSOLUTE_ORIENTATION_QUATERNION = ABSOLUTE_ORIENTATION_EULER_ANGLES + 1;

    public static final int RELATIVE_ORIENTATION_EULER_ANGLES = ABSOLUTE_ORIENTATION_QUATERNION + 1;

    public static final int RELATIVE_ORIENTATION_QUATERNION = RELATIVE_ORIENTATION_EULER_ANGLES + 1;

    public static final int MIN_VALUE = (int) (0);
    public static final int MAX_VALUE = (int) (10);

    private static final boolean IS_EXTENSIBLE = false;

    public static boolean isKnownValue(int value) {
        switch (value) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
                return true;
        }
        return false;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value))
            return;

        throw new DeserializationException("Invalid enum value.");
    }

    private SensorType() {}

}