// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * <pre>
 * Set the value of an form element.
 * </pre>
 *
 * Protobuf type {@code autofill_assistant.SetFormFieldValueProto}
 */
public  final class SetFormFieldValueProto extends
    com.google.protobuf.GeneratedMessageLite<
        SetFormFieldValueProto, SetFormFieldValueProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.SetFormFieldValueProto)
    SetFormFieldValueProtoOrBuilder {
  private SetFormFieldValueProto() {
    value_ = emptyProtobufList();
  }
  public interface KeyPressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autofill_assistant.SetFormFieldValueProto.KeyPress)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    boolean hasText();
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    boolean hasKeycode();
    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    int getKeycode();

    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    boolean hasKeyboardInput();
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    java.lang.String getKeyboardInput();
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    com.google.protobuf.ByteString
        getKeyboardInputBytes();

    public org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.KeypressCase getKeypressCase();
  }
  /**
   * Protobuf type {@code autofill_assistant.SetFormFieldValueProto.KeyPress}
   */
  public  static final class KeyPress extends
      com.google.protobuf.GeneratedMessageLite<
          KeyPress, KeyPress.Builder> implements
      // @@protoc_insertion_point(message_implements:autofill_assistant.SetFormFieldValueProto.KeyPress)
      KeyPressOrBuilder {
    private KeyPress() {
    }
    private int bitField0_;
    private int keypressCase_ = 0;
    private java.lang.Object keypress_;
    public enum KeypressCase
        implements com.google.protobuf.Internal.EnumLite {
      TEXT(1),
      KEYCODE(2),
      KEYBOARD_INPUT(3),
      KEYPRESS_NOT_SET(0);
      private final int value;
      private KeypressCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static KeypressCase valueOf(int value) {
        return forNumber(value);
      }

      public static KeypressCase forNumber(int value) {
        switch (value) {
          case 1: return TEXT;
          case 2: return KEYCODE;
          case 3: return KEYBOARD_INPUT;
          case 0: return KEYPRESS_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public KeypressCase
    getKeypressCase() {
      return KeypressCase.forNumber(
          keypressCase_);
    }

    private void clearKeypress() {
      keypressCase_ = 0;
      keypress_ = null;
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    public boolean hasText() {
      return keypressCase_ == 1;
    }
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.String ref = "";
      if (keypressCase_ == 1) {
        ref = (java.lang.String) keypress_;
      }
      return ref;
    }
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.String ref = "";
      if (keypressCase_ == 1) {
        ref = (java.lang.String) keypress_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    private void setText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  keypressCase_ = 1;
      keypress_ = value;
    }
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    private void clearText() {
      if (keypressCase_ == 1) {
        keypressCase_ = 0;
        keypress_ = null;
      }
    }
    /**
     * <pre>
     * Text to insert as-is into a form field.
     * </pre>
     *
     * <code>optional string text = 1;</code>
     */
    private void setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  keypressCase_ = 1;
      keypress_ = value.toStringUtf8();
    }

    public static final int KEYCODE_FIELD_NUMBER = 2;
    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    public boolean hasKeycode() {
      return keypressCase_ == 2;
    }
    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    public int getKeycode() {
      if (keypressCase_ == 2) {
        return (java.lang.Integer) keypress_;
      }
      return 0;
    }
    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    private void setKeycode(int value) {
      keypressCase_ = 2;
      keypress_ = value;
    }
    /**
     * <pre>
     * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
     * </pre>
     *
     * <code>optional int32 keycode = 2;</code>
     */
    private void clearKeycode() {
      if (keypressCase_ == 2) {
        keypressCase_ = 0;
        keypress_ = null;
      }
    }

    public static final int KEYBOARD_INPUT_FIELD_NUMBER = 3;
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    public boolean hasKeyboardInput() {
      return keypressCase_ == 3;
    }
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    public java.lang.String getKeyboardInput() {
      java.lang.String ref = "";
      if (keypressCase_ == 3) {
        ref = (java.lang.String) keypress_;
      }
      return ref;
    }
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    public com.google.protobuf.ByteString
        getKeyboardInputBytes() {
      java.lang.String ref = "";
      if (keypressCase_ == 3) {
        ref = (java.lang.String) keypress_;
      }
      return com.google.protobuf.ByteString.copyFromUtf8(ref);
    }
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    private void setKeyboardInput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  keypressCase_ = 3;
      keypress_ = value;
    }
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    private void clearKeyboardInput() {
      if (keypressCase_ == 3) {
        keypressCase_ = 0;
        keypress_ = null;
      }
    }
    /**
     * <pre>
     * Text as generated by processing a virtual key code with a keyboard
     * layout. This can also be used for keyboard control sequences such
     * as "&#92;r" or "&#92;t".
     * </pre>
     *
     * <code>optional string keyboard_input = 3;</code>
     */
    private void setKeyboardInputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  keypressCase_ = 3;
      keypress_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (keypressCase_ == 1) {
        output.writeString(1, getText());
      }
      if (keypressCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) keypress_));
      }
      if (keypressCase_ == 3) {
        output.writeString(3, getKeyboardInput());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (keypressCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getText());
      }
      if (keypressCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) keypress_));
      }
      if (keypressCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getKeyboardInput());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code autofill_assistant.SetFormFieldValueProto.KeyPress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress, Builder> implements
        // @@protoc_insertion_point(builder_implements:autofill_assistant.SetFormFieldValueProto.KeyPress)
        org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPressOrBuilder {
      // Construct using org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public KeypressCase
          getKeypressCase() {
        return instance.getKeypressCase();
      }

      public Builder clearKeypress() {
        copyOnWrite();
        instance.clearKeypress();
        return this;
      }


      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public boolean hasText() {
        return instance.hasText();
      }
      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public java.lang.String getText() {
        return instance.getText();
      }
      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        return instance.getTextBytes();
      }
      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }
      /**
       * <pre>
       * Text to insert as-is into a form field.
       * </pre>
       *
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTextBytes(value);
        return this;
      }

      /**
       * <pre>
       * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
       * </pre>
       *
       * <code>optional int32 keycode = 2;</code>
       */
      public boolean hasKeycode() {
        return instance.hasKeycode();
      }
      /**
       * <pre>
       * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
       * </pre>
       *
       * <code>optional int32 keycode = 2;</code>
       */
      public int getKeycode() {
        return instance.getKeycode();
      }
      /**
       * <pre>
       * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
       * </pre>
       *
       * <code>optional int32 keycode = 2;</code>
       */
      public Builder setKeycode(int value) {
        copyOnWrite();
        instance.setKeycode(value);
        return this;
      }
      /**
       * <pre>
       * DEPRECATED: A single US-ASCII character (e.g., 13 for carriage return).
       * </pre>
       *
       * <code>optional int32 keycode = 2;</code>
       */
      public Builder clearKeycode() {
        copyOnWrite();
        instance.clearKeycode();
        return this;
      }

      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public boolean hasKeyboardInput() {
        return instance.hasKeyboardInput();
      }
      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public java.lang.String getKeyboardInput() {
        return instance.getKeyboardInput();
      }
      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public com.google.protobuf.ByteString
          getKeyboardInputBytes() {
        return instance.getKeyboardInputBytes();
      }
      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public Builder setKeyboardInput(
          java.lang.String value) {
        copyOnWrite();
        instance.setKeyboardInput(value);
        return this;
      }
      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public Builder clearKeyboardInput() {
        copyOnWrite();
        instance.clearKeyboardInput();
        return this;
      }
      /**
       * <pre>
       * Text as generated by processing a virtual key code with a keyboard
       * layout. This can also be used for keyboard control sequences such
       * as "&#92;r" or "&#92;t".
       * </pre>
       *
       * <code>optional string keyboard_input = 3;</code>
       */
      public Builder setKeyboardInputBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyboardInputBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:autofill_assistant.SetFormFieldValueProto.KeyPress)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress other = (org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress) arg1;
          switch (other.getKeypressCase()) {
            case TEXT: {
              keypress_ = visitor.visitOneofString(
                 keypressCase_ == 1, keypress_, other.keypress_);
              break;
            }
            case KEYCODE: {
              keypress_ = visitor.visitOneofInt(
                  keypressCase_ == 2, keypress_, other.keypress_);
              break;
            }
            case KEYBOARD_INPUT: {
              keypress_ = visitor.visitOneofString(
                 keypressCase_ == 3, keypress_, other.keypress_);
              break;
            }
            case KEYPRESS_NOT_SET: {
              visitor.visitOneofNotSet(keypressCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.keypressCase_ != 0) {
              keypressCase_ = other.keypressCase_;
            }
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  keypressCase_ = 1;
                  keypress_ = s;
                  break;
                }
                case 16: {
                  keypressCase_ = 2;
                  keypress_ = input.readInt32();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  keypressCase_ = 3;
                  keypress_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:autofill_assistant.SetFormFieldValueProto.KeyPress)
    private static final org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new KeyPress();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<KeyPress> PARSER;

    public static com.google.protobuf.Parser<KeyPress> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  public static final int ELEMENT_FIELD_NUMBER = 1;
  private org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto element_;
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  public boolean hasElement() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getElement() {
    return element_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.getDefaultInstance() : element_;
  }
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void setElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    element_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void setElement(
      org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
    element_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void mergeElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (element_ != null &&
        element_ != org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.getDefaultInstance()) {
      element_ =
        org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.newBuilder(element_).mergeFrom(value).buildPartial();
    } else {
      element_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * A reference to the form element whose value should be set.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void clearElement() {  element_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress> value_;
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  public java.util.List<org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress> getValueList() {
    return value_;
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  public java.util.List<? extends org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPressOrBuilder> 
      getValueOrBuilderList() {
    return value_;
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  public int getValueCount() {
    return value_.size();
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress getValue(int index) {
    return value_.get(index);
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPressOrBuilder getValueOrBuilder(
      int index) {
    return value_.get(index);
  }
  private void ensureValueIsMutable() {
    if (!value_.isModifiable()) {
      value_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(value_);
     }
  }

  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void setValue(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureValueIsMutable();
    value_.set(index, value);
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void setValue(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
    ensureValueIsMutable();
    value_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void addValue(org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureValueIsMutable();
    value_.add(value);
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void addValue(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureValueIsMutable();
    value_.add(index, value);
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void addValue(
      org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
    ensureValueIsMutable();
    value_.add(builderForValue.build());
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void addValue(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
    ensureValueIsMutable();
    value_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void addAllValue(
      java.lang.Iterable<? extends org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress> values) {
    ensureValueIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, value_);
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void clearValue() {
    value_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The value to set.
   * </pre>
   *
   * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
   */
  private void removeValue(int index) {
    ensureValueIsMutable();
    value_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getElement());
    }
    for (int i = 0; i < value_.size(); i++) {
      output.writeMessage(2, value_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElement());
    }
    for (int i = 0; i < value_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, value_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Set the value of an form element.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.SetFormFieldValueProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.SetFormFieldValueProto)
      org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public boolean hasElement() {
      return instance.hasElement();
    }
    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getElement() {
      return instance.getElement();
    }
    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder setElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.setElement(value);
      return this;
      }
    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder setElement(
        org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
      copyOnWrite();
      instance.setElement(builderForValue);
      return this;
    }
    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder mergeElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.mergeElement(value);
      return this;
    }
    /**
     * <pre>
     * A reference to the form element whose value should be set.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder clearElement() {  copyOnWrite();
      instance.clearElement();
      return this;
    }

    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public java.util.List<org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress> getValueList() {
      return java.util.Collections.unmodifiableList(
          instance.getValueList());
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public int getValueCount() {
      return instance.getValueCount();
    }/**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress getValue(int index) {
      return instance.getValue(index);
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder setValue(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
      copyOnWrite();
      instance.setValue(index, value);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder setValue(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
      copyOnWrite();
      instance.setValue(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder addValue(org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
      copyOnWrite();
      instance.addValue(value);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder addValue(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress value) {
      copyOnWrite();
      instance.addValue(index, value);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder addValue(
        org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
      copyOnWrite();
      instance.addValue(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder addValue(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.Builder builderForValue) {
      copyOnWrite();
      instance.addValue(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder addAllValue(
        java.lang.Iterable<? extends org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress> values) {
      copyOnWrite();
      instance.addAllValue(values);
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <pre>
     * The value to set.
     * </pre>
     *
     * <code>repeated .autofill_assistant.SetFormFieldValueProto.KeyPress value = 2;</code>
     */
    public Builder removeValue(int index) {
      copyOnWrite();
      instance.removeValue(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.SetFormFieldValueProto)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        value_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto other = (org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto) arg1;
        element_ = visitor.visitMessage(element_, other.element_);
        value_= visitor.visitList(value_, other.value_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = element_.toBuilder();
                }
                element_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(element_);
                  element_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                if (!value_.isModifiable()) {
                  value_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(value_);
                }
                value_.add(
                    input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.KeyPress.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.SetFormFieldValueProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SetFormFieldValueProto();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.SetFormFieldValueProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SetFormFieldValueProto> PARSER;

  public static com.google.protobuf.Parser<SetFormFieldValueProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

